name: Deploy nails-bot Backend

on:
  push:
    branches: [backend]
  pull_request:
    branches: [backend]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy using git clone to /var/www/testingnil6/github/backend/
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          PAT: ${{ secrets.PAT }}
        run: |
          sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "
          set -e
          if [ -d /var/www/testingnil6/github/backend/.git ]; then
            echo 'Repository exists. Fetching and pulling changes...'
            cd /var/www/testingnil6/github/backend
            git fetch
            git checkout backend
            git pull origin backend
          else
            echo 'Repository does not exist. Cloning fresh repository...'
            rm -rf /var/www/testingnil6/github/backend*
            git clone https://${USERNAME}:${PAT}@github.com/NIL-IT/nails-bot.git /var/www/testingnil6/github/backend
            cd /var/www/testingnil6/github/backend
            git checkout backend
          fi
          "

      - name: Move API files to /var/www/testingnil6/backend/
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "
          set -e
          if [ -d /var/www/testingnil6/github/backend/api ]; then
            echo 'Moving API files...'
            rm -rf /var/www/testingnil6/backend/*
            cp -r /var/www/testingnil6/github/backend/api /var/www/testingnil6/backend/
          else
            echo 'API folder does not exist. Skipping copy step.'
          fi
          "
