name: Deploy nails-bot

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy and build project
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          PAT: ${{ secrets.PAT }}
        run: |
          # Sync files using rsync (more reliable than git pull)
          sshpass -p "$PASSWORD" rsync -avz --delete \
            --exclude='.git' \
            --exclude='node_modules' \
            ./ $USERNAME@$HOST:/var/www/nails-bot/frontend/

          # Build project on server
          sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "
            cd /var/www/nails-bot/frontend/ && \
            npm ci && \
            npm run build && \
            chmod -R 755 /var/www/nails-bot/frontend/
          "
