name: Deploy nails-bot

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy repository to /var/www/testingnil6/github/frontend/
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          PAT: ${{ secrets.PAT }}
        run: |
          sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "
          if [ -d /var/www/testingnil6/github/frontend/.git ]; then
            cd /var/www/testingnil6/github/frontend && \
            git fetch && \
            git checkout main && \
            git pull origin main
          else
            rm -rf /var/www/testingnil6/github/frontend/* && \
            git clone https://$USERNAME:$PAT@github.com/NIL-IT/nails-bot.git /var/www/testingnil6/github/frontend && \
            cd /var/www/testingnil6/github/frontend && \
            git checkout main
          fi
          "

      - name: Build project using npm
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "
          cd /var/www/testingnil6/github/frontend && \
          npm install && \
          npm run build
          "

      - name: Move built files to /var/www/testingnil6/frontend/
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "
          rm -rf /var/www/testingnil6/frontend/* && \
          cp -r /var/www/testingnil6/github/frontend/dist/* /var/www/testingnil6/frontend/
          "
